export const ROUTES = {
  DASHBOARD: '/dashboard',
  APPOINTMENTS: '/appointments',
  CALENDAR: '/calendar',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  USERS: '/users',
  LOGIN: '/login',
  PROFILE: '/profile',
  VETERINARIANS: '/veterinarians',
  HOME: '/',
  PATIENTS: '/patients',
  API_HEALTH: '/api-health',
  CONTACTS: '/contacts',  CLINICS: '/clinics',
  CLINIC_CREATE: '/clinics/create',
  CLINIC_EDIT: '/clinics/edit',
  CLINIC_REGISTER: '/register-clinic',
  CLINIC_REGISTER_SUCCESS: '/register-clinic/success',
  PETS: '/pets',
  PET_CASES: '/pet-cases',
  REVIEWS: '/reviews',
  ROLE_DEMO: '/role-demo',
  RESOURCES: '/admin/resources',
  TRAINING: '/admin/training',
  HOUSEHOLD_SAFETY: '/admin/household-safety',
} as const;
