export const ROUTES: Record<string, string> = {
  DASHBOARD: '/dashboard',
  APPOINTMENTS: '/appointments',
  CALENDAR: '/calendar',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  USERS: '/users',
  LOGIN: '/login',
  PROFILE: '/profile',
  VETERINARIANS: '/veterinarians',
  HOME: '/',
  PATIENTS: '/patients',
  API_HEALTH: '/api-health',
  CLINICS: '/clinics',
  CLINIC_CREATE: '/clinics/create',
  CLINIC_EDIT: '/clinics/edit',
  PETS: '/pets',
  REVIEWS: '/reviews',
};
